# The Docker image that will be used to build your app
image: ruby:2.7

build html:
  stage: build
  tags:
    - newrunner
  script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install notebook nbconvert
  - jupyter nbconvert --to html *.ipynb
  artifacts:
    untracked: true
    when: on_success
    expire_in: 30 days
    
pages:
  dependencies:
    - "build html"
  script:
    - mv *.html build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
