pages:
  tags:
    - newrunner
    - python -m venv venv
    - source venv/bin/activate
    - pip install notebook nbconvert
    - jupyter nbconvert --to html *.ipynb
    - mv *.html public
  artifacts:
    paths:
      - public
    expire_in: 1 week